// Page manifest for assemble.mjs. Every shipped HTML document is generated
// from partials/ (head, header, footer) plus its content source:
//   - content: 'sections'      → concatenate sections/*.html (homepage)
//   - content: 'pages/x.html'  → the page's <main> inner content
// nav: which header item is highlighted. navExact: false marks an ancestor
// (aria-current="true" instead of "page"), e.g. a case-study detail page.
export default [
  {
    out: 'index.html',
    title: 'Emposo | Die Outcome Factory der Hays-Gruppe',
    description: 'Emposo macht Wandel beherrschbar: definierte Leistungen, messbare Ergebnisse und Werkvertrag mit Acceptance.',
    nav: 'home',
    bodyClass: 'wrap-anywhere',
    content: 'sections',
    scripts: ['00-core', '01-header', '02-intent-links', '03-connection-system', '06-work'],
  },
  {
    out: 'expertise/index.html',
    title: 'Expertise | Emposo',
    description: 'Engineering und Technology: acht Lieferdisziplinen für messbare Ergebnisse im Betrieb.',
    nav: 'expertise',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/index.html',
    title: 'Portfolio | Emposo',
    description: 'Das Emposo Portfolio: optimieren, transformieren, skalieren und verzahnen als Ergebnisverantwortung.',
    nav: 'portfolio',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'case-studies/index.html',
    title: 'Case Studies | Emposo',
    description: 'Case Studies von Emposo: Herausforderung, Lieferung und messbare Ergebnisse im Überblick.',
    nav: 'case-studies',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/case-studies.html',
    scripts: ['00-core', '01-header', '06-work'],
  },
  {
    out: 'case-studies/data2ai-platform/index.html',
    title: 'Data2AI Plattform | Case Study | Emposo',
    description: 'Case Study Data2AI Plattform: Aus verteilten Engineering-Daten wird produktive KI.',
    nav: 'case-studies',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/case-study-data2ai-platform.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'about-us/index.html',
    title: 'Über uns | Emposo',
    description: 'Emposo ist die Outcome Factory der Hays-Gruppe: klare Leistungen, Verantwortung bis zur Abnahme und skalierbare Delivery.',
    nav: 'about',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/about-us.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'branchen/index.html',
    title: 'Branchen | Emposo',
    description: 'Fünf Branchen, ein Anspruch: Engineering- und Technology-Leistungen, die im Betrieb Ihrer Branche ankommen — mit den Nachweisen, die dort zählen.',
    nav: 'branchen',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/branchen.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'karriere/index.html',
    title: 'Karriere | Emposo',
    description: 'Karriere bei Emposo: Verantwortung übernehmen und mit einem Team bis zum Ergebnis arbeiten — 250+ Mitarbeitende an 4 Standorten.',
    nav: 'karriere',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/karriere.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'kontakt/index.html',
    title: 'Kontakt | Emposo',
    description: 'Sprechen wir über Ihr Vorhaben: Optimierung, Transformation, Skalierung oder Karriere. Ihre Anfrage wird als E-Mail vorbereitet.',
    nav: 'kontakt',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/kontakt.html',
    scripts: ['00-core', '01-header', '02-intent-links', '06-work'],
  },
  {
    out: 'expertise/engineering/index.html',
    title: 'Engineering | Expertise | Emposo',
    description: 'Vier Engineering-Disziplinen: System Engineering & Entwicklung, Industrialisierung, Test & Validierung und Engineering Services.',
    nav: 'expertise',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise-engineering.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'expertise/technology/index.html',
    title: 'Technology | Expertise | Emposo',
    description: 'Vier Technology-Disziplinen: AI & Daten, Software, Cloud & Architecture, Cyber & Compliance und Enterprise Services.',
    nav: 'expertise',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise-technology.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'expertise/ai-daten/index.html',
    title: 'AI & Daten | Expertise | Emposo',
    description: 'AI-Transformation & Daten: Strategie, Knowledge Graphs, RAG, Datenplattformen und MLOps — bis zur produktiven KI-Anwendung.',
    nav: 'expertise',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise-ai-daten.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/optimieren/index.html',
    title: 'Wir optimieren | Portfolio | Emposo',
    description: 'Bestehende Leistungen zuverlässig übernehmen und messbar verbessern: stabiler, schneller, nachvollziehbar — mit klaren Service-Leveln.',
    nav: 'portfolio',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-optimieren.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/transformieren/index.html',
    title: 'Wir transformieren | Portfolio | Emposo',
    description: 'Technologie, Daten und Prozesse bis zum messbaren Ergebnis in die Produktivumgebung bringen — gerechnet, bevor investiert wird.',
    nav: 'portfolio',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-transformieren.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/skalieren/index.html',
    title: 'Wir skalieren | Portfolio | Emposo',
    description: 'Teams und Lösungen entlang des tatsächlichen Bedarfs ausbauen — mit Emposo als verantwortlichem Vertragspartner in einer Leistung.',
    nav: 'portfolio',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-skalieren.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/verzahnen/index.html',
    title: 'Wir verzahnen | Portfolio | Emposo',
    description: 'Branchenwissen und Technologie-Expertise verbinden: Business-Mehrwert im Betrieb statt getrennter Perspektiven.',
    nav: 'portfolio',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-verzahnen.html',
    scripts: ['00-core', '01-header'],
  },
];
