// Page manifest for assemble.mjs. Every shipped HTML document is generated
// from partials/ (head, header, footer) plus its content source:
//   - content: 'sections'      → concatenate sections/*.html (homepage)
//   - content: 'pages/x.html'  → the page's <main> inner content
// nav: which header item is highlighted. navExact: false marks an ancestor
// (aria-current="true" instead of "page"), e.g. a case-study detail page.
import { disciplines, industries, projects } from './content/site-data.mjs';
export default [
  {
    out: 'index.html',
    title: 'Emposo | Wir machen Wandel beherrschbar',
    description: 'Emposo macht Wandel beherrschbar: definierte Leistungen, messbare Ergebnisse und Werkvertrag mit Acceptance.',
    nav: 'home',
    bodyClass: 'wrap-anywhere',
    content: ['sections/02-hero.html', 'sections/02b-expertise.html', 'sections/04-about.html', 'sections/05-industries.html', 'sections/06-work.html', 'sections/03-models.html', 'sections/07b-sales-cta.html'],
    scripts: ['00-core', '01-header', '02-intent-links', '06-work', '07-countup'],
  },
  {
    out: 'expertise/index.html',
    title: 'Expertise | Emposo',
    description: 'Engineering und Technology: acht Lieferdisziplinen für messbare Ergebnisse im Betrieb.',
    nav: 'expertise',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/index.html',
    title: 'Leistungen | Emposo',
    description: 'Das Emposo Portfolio: optimieren, transformieren, skalieren und verzahnen als Ergebnisverantwortung.',
    nav: 'portfolio',
    bodyClass: 'subpage wrap-anywhere',
    content: ['pages/portfolio.html', 'sections/07aa-faq.html'],
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'case-studies/index.html',
    title: 'Case Studies | Emposo',
    description: 'Case Studies von Emposo: Herausforderung, Lieferung und messbare Ergebnisse im Überblick.',
    nav: 'case-studies',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/case-studies.html',
    scripts: ['00-core', '01-header', '06-work'],
  },
  {
    out: 'case-studies/data2ai-platform/index.html',
    title: 'Data2AI Plattform | Case Study | Emposo',
    description: 'Case Study Data2AI Plattform: Aus verteilten Engineering-Daten wird produktive KI.',
    nav: 'case-studies',
    navExact: false,
    bodyClass: 'subpage wrap-anywhere',
    content: 'project:data2ai-platform',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'about-us/index.html',
    title: 'Über uns | Emposo',
    description: 'Emposo ist die Outcome Factory im Hays-Netzwerk: klare Leistungen, Verantwortung bis zur Abnahme und skalierbare Delivery.',
    nav: 'about',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/about-us.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'branchen/index.html',
    title: 'Branchen | Emposo',
    description: 'Fünf Branchen, ein Anspruch: Engineering- und Technology-Leistungen, die im Betrieb Ihrer Branche ankommen — mit den Nachweisen, die dort zählen.',
    nav: 'branchen',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/branchen.html',
    scripts: ['00-core', '01-header', '06-work'],
  },
  {
    out: 'karriere/index.html',
    title: 'Karriere | Emposo',
    description: 'Karriere bei Emposo: Verantwortung übernehmen und mit einem Team bis zum Ergebnis arbeiten — 250+ Mitarbeitende an 4 Standorten.',
    nav: 'karriere',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/karriere.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'kontakt/index.html',
    title: 'Kontakt | Emposo',
    description: 'Sprechen wir über Ihr Vorhaben: Optimierung, Transformation, Skalierung oder Karriere. Ihre Anfrage wird als E-Mail vorbereitet.',
    nav: 'kontakt',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/kontakt.html',
    scripts: ['00-core', '01-header', '02-intent-links', '06-work'],
  },
  {
    out: 'expertise/engineering/index.html',
    title: 'Engineering | Expertise | Emposo',
    description: 'Vier Engineering-Disziplinen: System Engineering & Entwicklung, Industrialisierung, Test & Validierung und Engineering Services.',
    nav: 'expertise-engineering',
    navGroup: 'expertise',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise-engineering.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'expertise/technology/index.html',
    title: 'Technology | Expertise | Emposo',
    description: 'Vier Technology-Disziplinen: AI & Daten, Software, Cloud & Architecture, Cyber & Compliance und Enterprise Services.',
    nav: 'expertise-technology',
    navGroup: 'expertise',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise-technology.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'expertise/ai-daten/index.html',
    title: 'AI & Daten | Expertise | Emposo',
    description: 'AI-Transformation & Daten: Strategie, Knowledge Graphs, RAG, Datenplattformen und MLOps — bis zur produktiven KI-Anwendung.',
    nav: 'expertise-ai-daten',
    navGroup: 'expertise',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/expertise-ai-daten.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/optimieren/index.html',
    title: 'Wir optimieren | Portfolio | Emposo',
    description: 'Bestehende Leistungen zuverlässig übernehmen und messbar verbessern: stabiler, schneller, nachvollziehbar — mit klaren Service-Leveln.',
    nav: 'portfolio-optimieren',
    navGroup: 'portfolio',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-optimieren.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/transformieren/index.html',
    title: 'Wir transformieren | Portfolio | Emposo',
    description: 'Technologie, Daten und Prozesse bis zum messbaren Ergebnis in die Produktivumgebung bringen — gerechnet, bevor investiert wird.',
    nav: 'portfolio-transformieren',
    navGroup: 'portfolio',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-transformieren.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/skalieren/index.html',
    title: 'Wir skalieren | Portfolio | Emposo',
    description: 'Teams und Lösungen entlang des tatsächlichen Bedarfs ausbauen — mit Emposo als verantwortlichem Vertragspartner in einer Leistung.',
    nav: 'portfolio-skalieren',
    navGroup: 'portfolio',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-skalieren.html',
    scripts: ['00-core', '01-header'],
  },
  {
    // serve-handler (and most static hosts) deliver /404.html for missing
    // paths with the correct 404 status.
    out: '404.html',
    title: 'Seite nicht gefunden | Emposo',
    description: 'Die angeforderte Seite existiert nicht. Diese Wege führen zurück zu Expertise, Portfolio, Case Studies und Kontakt.',
    nav: 'none',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/404.html',
    scripts: ['00-core', '01-header'],
  },
  {
    out: 'portfolio/verzahnen/index.html',
    title: 'Wir verzahnen | Portfolio | Emposo',
    description: 'Branchenwissen und Technologie-Expertise verbinden: Business-Mehrwert im Betrieb statt getrennter Perspektiven.',
    nav: 'portfolio-verzahnen',
    navGroup: 'portfolio',
    bodyClass: 'subpage wrap-anywhere',
    content: 'pages/portfolio-verzahnen.html',
    scripts: ['00-core', '01-header'],
  },
  ...projects.filter(project=>project.slug !== 'data2ai-platform').map(project=>({
    out:`case-studies/${project.slug}/index.html`, title:`${project.name} | Case Study | Emposo`,
    description:project.headline, nav:'case-studies', navExact:false,
    bodyClass:'subpage wrap-anywhere', content:`project:${project.slug}`, scripts:['00-core','01-header'],
  })),
  // One detail page per delivery discipline (workbook: every expertise is its
  // own portfolio category). ai-daten keeps its richer hand-authored page.
  ...disciplines.filter(discipline=>discipline.slug !== 'ai-daten').map(discipline=>({
    out:`expertise/${discipline.slug}/index.html`, title:`${discipline.name} | Expertise | Emposo`,
    description:discipline.promise, nav:'expertise', navExact:false,
    bodyClass:'subpage wrap-anywhere', content:`discipline:${discipline.slug}`, scripts:['00-core','01-header'],
  })),
  ...industries.map(industry=>({
    out:`branchen/${industry.slug}/index.html`, title:`${industry.name} | Emposo`,
    description:industry.intro, nav:'branchen', navExact:false,
    bodyClass:'subpage wrap-anywhere', content:`industry:${industry.slug}`, scripts:['00-core','01-header'],
  })),
  ...['cookies','barrierefreiheit','sitemap','zertifizierungen'].map(name=>({
    out:`${name}/index.html`, title:`${{cookies:'Cookies',sitemap:'Sitemap',barrierefreiheit:'Barrierefreiheit',zertifizierungen:'Zertifizierungen'}[name]} | Emposo`,
    description:name==='zertifizierungen'
      ? 'Zertifizierungen und Nachweise von Emposo: ISO 9001, TISAX-Assessment, Standards, Methoden und Compliant Sourcing®.'
      : 'Informationen zur Emposo Website.',
    nav:'none', bodyClass:'subpage wrap-anywhere',
    content:`pages/${name}.html`, scripts:['00-core','01-header'],
  })),
];
