// Editorial sources: Emposo_Website Struktur (2).xlsx (visible sheets, final
// proposal columns) and 2026-09-24-emposo-reference-cases-v14 (reference cases).
// Keep project claims in this one place.
// Disciplines have no detail pages (owner IA: "Es gibt keine Unternavigation/
// Unterseite für z. B. Engineering oder Technology") — they render as static
// cards on the Leistungen page. `focus` and `detail` are currently unrendered
// but kept as the workbook's editorial source (Unterpunkte/statement columns).
export const disciplines = [
  {slug:'system-engineering', name:'System Engineering & Entwicklung', group:'Engineering', icon:'cpu-line', topics:'Anforderungen, Modellierung, Entwicklung und Embedded Systems.', focus:['Anforderungen','Modellierung','Entwicklung','Embedded Systems'], detail:'Anforderungen, Modellierung, Entwicklung und Embedded Systems werden zu einer abgesicherten Funktion verbunden — als definierter Umfang mit Abnahme.', promise:'Wir übernehmen definierte Entwicklungsumfänge von der Anforderung bis zur abgesicherten Funktion.'},
  {slug:'produktion-industrialisierung', name:'Produktion & Industrialisierung', group:'Engineering', icon:'factory-line', topics:'Qualität, Logistik, Automatisierung, Anlagenintegration und Prozessoptimierung.', focus:['Qualität','Logistik','Automatisierung','Anlagenintegration','Prozessoptimierung'], detail:'Qualität, Logistik, Automatisierung, Anlagenintegration und Prozessoptimierung greifen ineinander, damit technische Abläufe stabil laufen.', promise:'Wir industrialisieren Prozesse, Datenflüsse und technische Abläufe für einen stabilen Betrieb.'},
  {slug:'test-validierung', name:'Test, Validierung & Integration', group:'Engineering', icon:'clipboard-check-line', topics:'Integration und Test, Safety, Quality Gates und revisionssichere Nachweise.', focus:['Teststrategie','Testautomatisierung','Integration','Safety','Quality Gates','Revisionssichere Nachweise'], detail:'Teststrategie, Automatisierung, Integration und Safety führen zu Quality Gates und revisionssicheren Nachweisen für belastbare Freigaben.', promise:'Wir machen Qualität, Sicherheit und Freigabeentscheidungen belastbar.'},
  {slug:'engineering-services', name:'Engineering Services', group:'Engineering', icon:'documents-2-line', topics:'PMO, Change, Audit und technische Dokumentation.', focus:['PMO','Change','Audit','Technische Dokumentation','Reporting','Konfigurationsmanagement'], detail:'PMO, Change, Audit, technische Dokumentation, Reporting und Konfigurationsmanagement — als Dauerleistung mit klar abgegrenztem Ergebnis.', promise:'Wir liefern technische Steuerung und Dokumentation als messbare, abgegrenzte Werkleistung.'},
  {slug:'ai-daten', name:'AI-Transformation & Daten', group:'Technology', icon:'brain-ai-line', topics:'AI-Strategie, Agentic AI, Datenplattformen, MLOps und Training.', focus:['AI-Strategie','Agentic AI','Knowledge Graphs','RAG','Datenplattformen','MLOps','Training'], detail:'AI-Strategie, Agentic AI, Knowledge Graphs, Datenplattformen und MLOps führen Daten und Wissen in produktive Anwendungen.', promise:'Wir überführen Daten und Wissen in produktive, nachvollziehbare AI-Anwendungen.'},
  {slug:'software-cloud', name:'Software, Cloud & Architecture', group:'Technology', icon:'cloud-connect-line', topics:'Solution Architecture, Multi-Cloud, Fullstack und DevSecOps.', focus:['Solution Architecture','Multi-Cloud','Fullstack','APIs','CI/CD','DevSecOps','Plattformintegration'], detail:'Solution Architecture, Multi-Cloud, Fullstack-Entwicklung, APIs, CI/CD und DevSecOps tragen Plattformen und Anwendungen bis in den produktiven Betrieb.', promise:'Wir bauen und transformieren Plattformen, Anwendungen und Architekturen bis zum produktiven Betrieb.'},
  {slug:'cyber-compliance', name:'Cyber & Compliance', group:'Technology', icon:'shield-lock-line', topics:'Cyber Security, Penetration Testing, GxP und EU AI Act.', focus:['Cyber Security','Security Architecture','Penetration Testing','GxP','EU AI Act','Auditfähige Nachweise'], detail:'Cyber Security, Security Architecture, Penetration Testing sowie GxP- und EU-AI-Act-Anforderungen werden Teil von Architektur, Prozessen und Lieferung.', promise:'Wir integrieren Sicherheit und Compliance in Architektur, Prozesse und Lieferung.'},
  {slug:'enterprise-services', name:'Enterprise Services', group:'Technology', icon:'server-line', topics:'Managed Services, Migration, Integration und S/4HANA.', focus:['Managed Services','Migration','Integration','S/4HANA','SLA-gesteuerter Betrieb'], detail:'Managed Services, Migration, Integration und S/4HANA — betrieben mit vereinbarten Service-Leveln, Reaktionszeiten und Eskalationswegen.', promise:'Wir übernehmen Migration, Integration und Betrieb mit klarer Service- und Ergebnisverantwortung.'},
];

export const industries = [
  {slug:'aerospace-defense', name:'Aerospace & Defense', image:'industry-aerospace', filter:'aerospace', intro:'Engineering, Integration und belastbare Nachweise für komplexe technische Systeme.', challenge:'Komplexe Systeme brauchen durchgängige Anforderungen, abgestimmte Entwicklungsprozesse und nachvollziehbare Freigaben.', delivery:'Wir verbinden Systementwicklung, Test und technische Dokumentation zu klar definierten Leistungen.', disciplines:['system-engineering','test-validierung','engineering-services'], cases:[]},
  {slug:'energy-resources', name:'Energy & Resources', image:'industry-energy', filter:'energy', intro:'Stabile Systeme und verlässliche Services für eine Branche im Wandel.', challenge:'Kritische Prozesse müssen zuverlässig laufen, während sich Technologien und Anforderungen weiterentwickeln.', delivery:'Wir übernehmen Integration und laufende Services mit vereinbarten Service-Leveln, Reaktionszeiten und Eskalationswegen.', disciplines:['software-cloud','enterprise-services'], cases:['managed-service','virtuelles-kraftwerk']},
  {slug:'health-pharma', name:'Health & Pharma', image:'industry-health', filter:'health', intro:'Technologie, Validierung und Qualität im regulierten Umfeld.', challenge:'Neue Technologien und aktualisierte KI-Modelle müssen sich in geregelte Prüf- und Freigabeprozesse einfügen.', delivery:'Wir verzahnen AI, Test und Compliance mit den Anforderungen Ihrer produktiven Umgebung.', disciplines:['test-validierung','ai-daten','cyber-compliance'], cases:['mlops-medizinprodukte','multi-site-transition','qualitaetsarbeit-pharma-diagnostik','cybersecurity-post-market','informationssicherheits-risikomanagement']},
  {slug:'industrials-manufacturing', name:'Industrials & Manufacturing', subtitle:'Inklusive Automotive', image:'industry-industrials', filter:'industrial', intro:'Von der Fahrzeugentwicklung bis zum Werk: Engineering und Technology greifen ineinander.', challenge:'Verteiltes Engineering-Wissen, komplexe Fahrzeugfunktionen und industrielle Abläufe brauchen eine gemeinsame technische Grundlage.', delivery:'Wir verbinden Entwicklung, Produktion, Tests und Daten, damit Wissen nutzbar wird und Prozesse stabil laufen.', disciplines:['system-engineering','produktion-industrialisierung','test-validierung','engineering-services','ai-daten'], cases:['data2ai-platform','engineering-wissensbasis','wissens-assistent','homologationstests','rechenzentrums-umzug','software-planung-antriebssteuergeraete','gewichtsmanagement-sportwagen','ki-testspezifikation','auslagerung-zerspanung','technische-dokumentation-antriebsumrichter','plattformen-kreislaufwirtschaft','funktionsbetreuung-infotainment','penetrationstests']},
  {slug:'technology-telecoms-media', name:'Technology, Telecoms & Media', image:'industry-technology', filter:'technology', intro:'Digitale Produkte, sichere Plattformen und skalierbare Architekturen.', challenge:'Anwendungen, Daten und bestehende Systeme müssen sich auch bei wachsenden Anforderungen zuverlässig verbinden lassen.', delivery:'Wir führen Software, Cloud, Security und Datenkompetenz bis zum produktiven Betrieb zusammen.', disciplines:['ai-daten','software-cloud','cyber-compliance','enterprise-services'], cases:['technische-dokumentation-halbleiter','projektsteuerung-chip-entwicklung','fuzzing-firmware','penetrationstests']},
];

export const projects = [
  {slug:'data2ai-platform', name:'Data2AI Plattform', headline:'Aus verteilten Engineering-Daten wird produktive KI.', industry:'Automotive', filter:'industrial automotive', outcome:'transform', discipline:'ai-daten', image:'data2ai', metric:'7×', label:'Produktivitätssteigerung', challenge:'Verteilte Engineering-Daten sollen als gemeinsame Grundlage für produktive KI nutzbar werden.', solution:'Eine Data2AI Plattform verbindet Engineering-Daten und Wissen für die Anwendung im Betrieb.', results:['7-fache Produktivitätssteigerung','ROI innerhalb von 9 Monaten','PoC in weniger als 4 Wochen']},
  {slug:'engineering-wissensbasis', name:'Vernetzte Engineering-Wissensbasis', headline:'Von Wochen auf Stunden: Engineering-Wissen wird ausführbar.', industry:'Automotive', filter:'industrial automotive', outcome:'transform', discipline:'ai-daten', image:'engineering-knowledge', metric:'83 %', label:'weniger Aufwand bei Testspezifikationen', challenge:'Engineering-Wissen muss für Testspezifikationen verfügbar und über die Entwicklung hinweg nachvollziehbar sein.', solution:'Eine vernetzte Wissensbasis macht Engineering-Wissen ausführbar und unterstützt die Erstellung von Testspezifikationen.', results:['83 % weniger Aufwand bei Testspezifikationen','Vollständige Traceability']},
  {slug:'rechenzentrums-umzug', name:'Rechenzentrums-Umzug ohne Stillstand', headline:'Transformation ohne eine Minute migrationsbedingten Stillstand.', industry:'Automotive', filter:'industrial automotive', outcome:'transform', discipline:'enterprise-services', image:'datacenter', metric:'0', label:'Minuten migrationsbedingter Stillstand', challenge:'Ein Rechenzentrum muss umziehen, während Produktion und Logistik durchgängig verfügbar bleiben.', solution:'Migration und Integration werden auf den fortlaufenden Betrieb von Produktion und Logistik ausgerichtet.', results:['Keine migrationsbedingte Betriebsunterbrechung','Produktion und Logistik durchgängig verfügbar']},
  {slug:'mlops-medizinprodukte', name:'MLOps für Medizinprodukte', headline:'KI-Modelle regulatorisch sicher und schneller aktualisieren.', industry:'Health & Pharma', filter:'health', outcome:'transform', discipline:'ai-daten', image:'pharma', metric:'>70 %', label:'weniger Prüfaufwand', challenge:'KI-Modelle für Medizinprodukte müssen aktualisiert und ihre Änderungen regulatorisch sicher geprüft werden.', solution:'MLOps verbindet die Aktualisierung der KI-Modelle mit den notwendigen Prüf- und Freigabeabläufen.', results:['Über 70 % weniger Prüfaufwand','Updates in Tagen statt Wochen']},
  {slug:'wissens-assistent', name:'Wissens-Assistent Engineering', headline:'Technisches Wissen in Sekunden statt Tagen verfügbar.', industry:'Industrials & Manufacturing', filter:'industrial', outcome:'transform', discipline:'ai-daten', image:'software', metric:'80.000 €', label:'bis zu dieser Summe monatlich an Rechercheaufwand eingespart', challenge:'Die Recherche nach technischem Wissen bindet Zeit in der täglichen Engineering-Arbeit.', solution:'Ein Wissens-Assistent macht technisches Wissen für die tägliche Anwendung verfügbar.', results:['Technisches Wissen in Sekunden statt Tagen verfügbar','Bis zu 80.000 EUR Rechercheaufwand pro Monat eingespart']},
  {slug:'multi-site-transition', name:'Multi-Site Transition Program', headline:'27+ Beauftragungen termingerecht und auditfest abgenommen.', industry:'Health & Pharma', filter:'health', outcome:'scale', discipline:'cyber-compliance', image:'pharma-transition', metric:'27+', label:'Beauftragungen termingerecht und auditfest abgenommen', challenge:'Ein Transition-Programm muss über mehrere Standorte hinweg termingerecht und auditfest umgesetzt werden.', solution:'Ein standortübergreifendes Programm führt die Beauftragungen zur Abnahme und schafft einen wiederverwendbaren Rollout-Blueprint.', results:['27+ Beauftragungen termingerecht und auditfest abgenommen','Quality-Team entlastet','Rollout-Blueprint für weitere Standorte etabliert']},
  {slug:'homologationstests', name:'Zulassungs- und Homologationstests', headline:'Markteinführung über mehrere Fahrzeugwellen abgesichert.', industry:'Automotive', filter:'industrial automotive', outcome:'optimize', discipline:'test-validierung', image:'vehicle-testing', metric:'Zulassung', label:'termingerecht abgesichert', challenge:'Mehrere Fahrzeugwellen benötigen belastbare Tests und Nachweise für ihre Markteinführung.', solution:'Zulassungs- und Homologationstests sichern die Freigaben mit vollständigen revisionssicheren Nachweisen ab.', results:['Zulassungstermine eingehalten','Vollständige revisionssichere Nachweise']},
  {slug:'managed-service', name:'Managed Service seit 2018', headline:'Langfristige Betriebssicherheit mit klaren SLAs.', industry:'Energy & Resources', filter:'energy', outcome:'optimize', discipline:'enterprise-services', image:'wind-energy', metric:'8+', label:'Jahre stabiler Betrieb', challenge:'Ein laufender Service braucht dauerhaft verlässliche Leistung und klar definierte Service-Level.', solution:'Ein langfristiger Managed Service übernimmt den Betrieb mit klar vereinbarten SLAs.', results:['Über 8 Jahre stabiler Betrieb','Keine SLA-Verletzungen']},
  // 2026-09-24 reference-cases deck (owner delivery 2026-09-26, rev. 3, 15 cases,
  // bullets verbatim; facts = the deck's "Projekt" box, its " I " separators split
  // into items). Two deck cases replace the workbook's technische-dokumentation and
  // fahrzeugfunktionen (owner 2026-09-26). metric/label/industry labels are drafts.
  {slug:"software-planung-antriebssteuergeraete", name:"Software-Planung für Antriebssteuergeräte", headline:"Rund 100 Software-Ablieferungen pro Jahr geplant und verfolgt", industry:"Automotive", filter:"industrial automotive", outcome:"optimize", discipline:"engineering-services", image:"antriebssteuerung", metric:"100", label:"Software-Ablieferungen pro Jahr",
    facts:[
      "Premium-Automobilhersteller, Antriebselektronik an drei Standorten",
      "Steuergeräte für V6- und V8-Motoren, Diesel und Otto, auch elektrifiziert",
      "Software-Inhaltsplanung, Änderungsdokumentation und Beifangbewertung als Werk",
      "Projekt: 36 Monate",
      "ca. 880.000 €",
      "Einheitspreise, quartalsweise abgenommen",
    ],
    challenge:[
      "Rund 100 Software-Ablieferungen pro Jahr: 30 Serienpflege, 70 Neuentwicklung",
      "Jede Änderung nach Konzernprozess dokumentieren, auf Nebenwirkungen prüfen, terminieren",
      "Anforderer, Systemlieferant und Terminplan hängen voneinander ab",
      "Übernahme vom Vorgängergewerk in drei Monaten ohne Bruch",
    ],
    solution:[
      "Software-Inhalte je Ablieferung planen, verfolgen und für alle sichtbar halten",
      "Änderungsdokumentation und Beifangbewertung nach Konzernprozess, auch homologationsrelevant",
      "Requirements Engineering im Steuergerät, Problemverfolgung in den Kundentools",
      "Wöchentliche Statusberichte und Status-Folien für die Gremien",
    ],
    results:[
      "Alle Leistungspositionen 2023 bis 2025 quartalsweise abgenommen",
      "Rahmenvertrag bis 11/2027 verlängert, Rahmenwert auf rund 1,6 Mio. € erhöht",
      "Übergabe und Abschlussdokumentation vertraglich verankert",
    ]},
  {slug:"gewichtsmanagement-sportwagen", name:"Gewichtsmanagement für Premium-Sportwagen", headline:"Gewichtsdaten über den gesamten Produktentstehungsprozess, seit 2016", industry:"Automotive", filter:"industrial automotive", outcome:"optimize verzahnen", discipline:"system-engineering", image:"gewichtsmanagement", metric:"10", label:"Jahre durchgehend beauftragt",
    facts:[
      "Premium-Sportwagen-Hersteller, Gesamtfahrzeugentwicklung",
      "Alle Baureihen: Basisumfang plus Derivate, zwölf Meilensteine je Fahrzeugprojekt",
      "Seit 2016 in Folge beauftragt",
      "Aktuelle Phase: 4 Geschäftsjahre",
      "ca. 670.000 €",
      "Festpreis je Meilenstein mit Abnahme",
    ],
    challenge:[
      "Jede Konstruktionsänderung verändert Gewicht und Schwerpunkt jeder Variante",
      "Gewichtsziele je Derivat vom Projektstart bis zum Modelleinsatz nachhalten",
      "Eine Datenbasis, der Konstruktion, Programmsteuerung und Fahrwerk vertrauen",
    ],
    solution:[
      "Gewichtsprognose je Meilenstein, Ausstattungsoptionen auf Sachnummernebene",
      "Gewichtsbenchmark gegen den Wettbewerb, Wägung von Bauteilen und Fahrzeugen",
      "Massenträgheits- und Deviationsmomente für die Fahrwerksentwicklung",
      "Einzelaufgaben über Ticketsystem, Abnahme je Meilenstein",
    ],
    results:[
      "Alle Meilensteinlieferungen 2023 bis 2025 per Protokoll abgenommen",
      "Zehn Jahre durchgehend beauftragt, zuletzt für drei Konzernmarken",
      "Eine Datenbasis für Konstruktion, Fahrwerk und Programmsteuerung",
    ]},
  {slug:"qualitaetsarbeit-pharma-diagnostik", name:"Qualitätsarbeit für einen Pharma-Diagnostik-Konzern", headline:"Über 40 Festpreis-Pakete seit 2022 unter einem Werkrahmenvertrag", industry:"Health & Pharma", filter:"health", outcome:"scale optimize", discipline:"test-validierung", image:"pharma-qualitaet", metric:"40+", label:"Festpreis-Pakete seit 2022",
    facts:[
      "Pharma-Diagnostik-Konzern, Produktion und Labore an zwei deutschen Standorten",
      "Werkrahmenvertrag seit 2019, Projekteinzelvertrag je Paket",
      "Risikoanalysen, Qualifizierungsdokumentation, SOPs, CAPA, Equipment, Methodenverifizierung",
      "Umfang: über 40 Qualitätspakete seit 2022",
      "bis 170.000 € je Paket",
      "Abnahme alle zwei Monate",
    ],
    challenge:[
      "Prüf- und Dokumentationsaufgaben in vielen Fachbereichen zugleich, Kapazität fehlt",
      "Gerätebücher, Risikoanalysen und Qualifizierungsdokumente müssen prüfbar im Kundensystem liegen",
      "Jede Lücke gefährdet Freigaben, Audits und Lieferfähigkeit",
    ],
    solution:[
      "Jede Aufgabe als Paket mit Ergebnisliste, Festpreis und Abnahme",
      "Pharma-Qualitäter moderieren Risikoanalysen, verifizieren Methoden, prüfen nach GDP und ALCOA+",
      "Qualifizierungs- und Validierungsdokumentation, Equipment-Management mit Gerätebüchern",
      "SOPs, Abweichungen und CAPA, Batch Record Reviews; GMP-Verantwortung beim Kunden",
    ],
    results:[
      "Jedes Paket gegen seine Ergebnisliste abgenommen",
      "Fachbereiche bestellen seit 2019 nach, Change-Request-Ketten bis neun Verlängerungen",
      "Rückstände abgearbeitet, ohne dass der Kunde Personal aufbauen musste",
    ]},
  {slug:"ki-testspezifikation", name:"KI-gestützte Testspezifikation", headline:"Automatisierte Testgenerierung, zwei Piloten bei zwei Automobilherstellern", industry:"Automotive", filter:"industrial automotive", outcome:"verzahnen transform", discipline:"ai-daten", image:"ki-testspezifikation", metric:"2", label:"Piloten bei zwei Automobilherstellern",
    facts:[
      "Zwei Automobilhersteller, Premium und Volumen: Testspezifikation und Infotainment-Diagnose",
      "Ausgangsbasis: Spezifikationen, Testfälle und Diagnosedaten, rund 1.800 Testfälle",
      "Testfallgenerierung mit KI-Agenten auf der Emposo-Plattform Data2AI",
      "Pilot 1: 3 Monate, ca. 50.000 €, abgenommen",
      "Pilot 2: 6 Monate, ca. 33.000 €, läuft",
      "Festpreis",
    ],
    challenge:[
      "Testfälle entstehen von Hand aus Anforderungen und Diagnosespezifikationen",
      "Umsetzbarkeit soll an realen Daten nachgewiesen werden, nicht an Beispielen",
      "Ergebnisse müssen ohne Nachbearbeitung in der Testautomatisierung laufen",
    ],
    solution:[
      "KI-Agenten übersetzen Anforderungen in strukturierte, ausführbare Testfälle im Zielformat",
      "Fachleute prüfen und bewerten, Abnahme anhand der gelieferten Testfälle",
      "Installation in der Kundenumgebung mit CI/CD oder Betrieb auf Emposo-IT unter TISAX",
      "Beauftragt unter den KI-Anforderungen des Kunden-Lastenhefts (EU AI Act)",
    ],
    results:[
      "Pilot 1 fristgerecht geliefert und vollständig abgenommen",
      "Zweiter Hersteller beauftragt sechs Monate später denselben Ansatz",
      "Testfälle laufen im Format der Kunden-Testautomatisierung",
    ]},
  {slug:"technische-dokumentation-halbleiter", name:"Technische Dokumentation als Werkleistung", headline:"Rahmenabruf im siebten Jahr, Volumen mehr als verzehnfacht", industry:"Halbleiter", filter:"technology", outcome:"scale optimize", discipline:"engineering-services", image:"technische-dokumentation-dita", metric:">10×", label:"Abrufvolumen seit 2020",
    facts:[
      "Globaler Halbleiterhersteller, Dokumentations-Servicebereich der Entwicklung",
      "Handbücher, Datenblätter, Errata Sheets, Application Notes, Security Guidelines",
      "Migration ins XML/DITA-Redaktionssystem und Toolentwicklung für die Redaktion",
      "Jahresabrufe seit 2020, aktuell 803.000 € pro Jahr",
      "Werk mit Rahmenabruf",
      "Abnahme je Ticket",
    ],
    challenge:[
      "Dokumentation muss zur Produktfreigabe fertig sein, der Bedarf schwankt mit den Produktzyklen",
      "Bestand aus FrameMaker und Word nach DITA migrieren, bei laufender Redaktion",
      "Produkt- und Terminologiewissen über Jahre stabil halten",
    ],
    solution:[
      "Jedes Paket als Ticket: Komplexität abgestimmt, schriftliche Abnahme, zwei Jahre Gewährleistung",
      "Eingespieltes Redaktionsteam in der Publikationskette des Kunden",
      "Konvertierung, Validierung und Testimport ins XML/DITA-System",
      "Toolentwicklung: XSLT, DITA-Plug-ins, Word-Templates, Terminologiepflege",
    ],
    results:[
      "Acht Jahresabrufe in Folge, Abruf 2026/27 mit 400.000 € bereits erteilt",
      "Abrufvolumen von 59.000 € auf 803.000 € pro Jahr gewachsen",
      "Kunde zahlt nur abgenommene Pakete, keine Mindestabnahme, keine Fixkosten",
    ]},
  {slug:"projektsteuerung-chip-entwicklung", name:"Projektsteuerung für Chip-Entwicklungsprojekte", headline:"PMO als Werkleistung in eigenen Räumen, vier Folgepakete", industry:"Halbleiter", filter:"technology", outcome:"optimize", discipline:"engineering-services", image:"projektsteuerung", metric:"4", label:"Folgepakete zum Festpreis",
    facts:[
      "Globaler Halbleiterhersteller, Automotive-Mikrocontroller, Forschung und Entwicklung",
      "Operatives Projektmanagement für bis zu sechs parallele Chip-Projekte",
      "Leistung in Emposo-Räumen, der Kunde stellt die IT-Zugänge",
      "März 2022 bis Dezember 2024, vier Pakete",
      "ca. 680.000 €",
      "Festpreis, schriftliche Abnahme",
    ],
    challenge:[
      "Formaler Meilensteinprozess verlangt lückenlose Projektdaten zu Kosten, Terminen, Risiken",
      "Wiederkehrende Arbeit je Meilenstein bindet die Projektleiter",
      "Externe Einzelkräfte bedeuten Wissensverlust bei jedem Wechsel",
    ],
    solution:[
      "Projektdaten in den Kundensystemen: KLUSA, Windchill, Jira, MS Project, Release Manager",
      "Meilensteinprozess vorbereiten und durchführen, Fortschritt berichten",
      "Statusberichte, Action-Item-Listen, Change-Ticket-Status für die Projektleiter",
      "DFMEA-Koordination in Aris und PLATO, Plausibilitätsprüfung der Daten",
    ],
    results:[
      "Vier Festpreispakete in Folge, Halbjahresvolumen von 68.000 € auf 189.000 €",
      "Jedes Paket schriftlich abgenommen, Mehrbedarf über Change Request",
      "Projektleiter entscheiden, der Meilensteinprozess läuft im Emposo-Projektbüro",
    ]},
  {slug:"auslagerung-zerspanung", name:"Auslagerung von Zerspanungsleistungen", headline:"Lieferantenauswahl und Know-how-Transfer in drei Arbeitspaketen", industry:"Industrials & Manufacturing", filter:"industrial", outcome:"transform verzahnen", discipline:"produktion-industrialisierung", image:"lieferanten-entwicklung", metric:"3", label:"Arbeitspakete bis zur Endabnahme",
    facts:[
      "Hersteller von Vakuumtechnik, Auftraggeber ist die Produktionsleitung",
      "Auslagerung von Dreh-, Fräs- und Dreh-Fräs-Leistungen an externe Lieferanten",
      "Koordination von Produktion, Einkauf, Supply Chain, Qualität und Lieferanten vor Ort",
      "Projekt: ca. 5 Monate",
      "ca. 75.000 €",
      "Festpreis, Werkabnahme gegen Lastenheft",
    ],
    challenge:[
      "Geeignete Lieferanten finden, bewerten und qualifizieren",
      "Fertigungs- und Prozesswissen der Bediener und NC-Programmierer vollständig übertragen",
      "Termine, Mengen und Qualität über alle Beteiligten steuern",
    ],
    solution:[
      "Lieferantenliste aufgebaut, bewertet, geclustert, Lieferantenbesuche vor Ort",
      "Angebote eingeholt, verglichen, Empfehlung ausgesprochen",
      "Prozessanalyse, Schulungsunterlagen und Key-User-Schulungen",
      "Termin- und Mengenkoordination, Statusbericht alle zwei Wochen, Mängelstatus wöchentlich",
    ],
    results:[
      "Qualifizierte Lieferantenbasis mit Empfehlung an die Produktionsleitung",
      "Fertigungswissen in Schulungsunterlagen und Schulungen übertragen",
      "Drei Arbeitspakete, Zahlung an Meilensteine und Endabnahme gekoppelt",
    ]},
  {slug:"technische-dokumentation-antriebsumrichter", name:"Technische Dokumentation für Antriebsumrichter", headline:"Security-Leitfaden und Betriebsanleitungen für zwei neue Umrichterfamilien", industry:"Industrials & Manufacturing", filter:"industrial", outcome:"optimize", discipline:"engineering-services", image:"betriebsanleitung", metric:"3×", label:"Volumen im Folgeauftrag 2025",
    facts:[
      "Globaler Technologiekonzern, Antriebstechnik, Umrichter für Motion Control",
      "2023: Projektierungshandbuch Industrial Security für zwei Softwarestände",
      "2025/26: Betriebsanleitungen zweier Umrichterfamilien, Emposo als Information Manager",
      "2023 Kontingent 400 h, ca. 63.000 €",
      "2025/26 Festpreis, ca. 197.000 €",
      "dritter Auftrag im Angebot",
    ],
    challenge:[
      "Industrial Security für Anwender verständlich, entwicklungsbegleitend aus Pflichtenheften",
      "Komplette Betriebsanleitungen zum Meilenstein der Produktfreigabe",
      "Redaktionskette des Kunden: Templates, linguistische Prüfung, Grafik, sechs Sprachen",
    ],
    solution:[
      "Security-Funktionen aus den Pflichtenheften recherchiert, als Handbuch aufbereitet",
      "Redaktion in den Kundensystemen, Grafiken über das Motivcenter, Steuerung in Azure DevOps",
      "Ausgabe als PDF und HTML5 in sechs Sprachen",
      "Ab 2025 Information Manager: Emposo steuert und prüft die Redakteure",
    ],
    results:[
      "Handbuch Industrial Security in zwei Ausgaben und sechs Sprachen veröffentlicht",
      "Folgeauftrag 2025 mit dreifachem Volumen zum Produktmeilenstein",
      "Rahmenverträge seit 2011 und 2018, dritte Beauftragung in Vorbereitung",
    ]},
  {slug:"virtuelles-kraftwerk", name:"Virtuelles Kraftwerk", headline:"78 Festpreis-Sprints in drei Jahren, seit 2025 als agiles Team fortgeführt", industry:"Energy & Resources", filter:"energy", outcome:"scale transform", discipline:"software-cloud", image:"virtuelles-kraftwerk", metric:"78", label:"Festpreis-Sprints in drei Jahren",
    facts:[
      "Betreiber eines virtuellen Kraftwerks: rund 5.000 Anlagen mit etwa 5.000 MW (Kundenangabe)",
      "Weiterentwicklung der Plattform: Prognosen, Einsatzoptimierung, Kundenportal, öffentliche API",
      "Rahmenvertrag für agile Projekte mit Sprint-Einzelverträgen und Defektklassen",
      "06/2022 bis 04/2025: 78 Sprints, 2,2 Mio. € Festpreis",
      "seit 2025 agiles Team, verlängert bis Ende 2026",
    ],
    challenge:[
      "Plattform über Jahre weiterentwickeln, ohne dass der Energiehandel stillsteht",
      "Jeder Sprint braucht ein abnahmefähiges Inkrement: kein Defekt der Klassen 1 und 2",
      "Prognosen und erlösoptimierte Fahrpläne in die bestehende Systemlandschaft einpassen",
    ],
    solution:[
      "Jeder Sprint ein Einzelvertrag mit Abnahmekriterien, Abnahme je Sprint, Vertragsstrafe bei Verzug",
      "Prognosen, Einsatzoptimierung, öffentliche API, Endkundenportal in React",
      "Schnittstellen zu Vertrieb und Abrechnung, Stammdatenbank mit Adapter",
      "Übergang 04/2025 in die Fortführung ohne Unterbrechung, gleiche Projektleitung",
    ],
    results:[
      "78 Sprints in 34 Monaten abgenommen, 2,2 Mio. € zum Festpreis",
      "Fortführung seit 2025 zweimal verlängert, aktuell bis Ende 2026",
      "Kunde beauftragt 2023 zusätzlich den Penetrationstest der Plattform",
    ]},
  {slug:"plattformen-kreislaufwirtschaft", name:"Digitale Plattformen für die Kreislaufwirtschaft", headline:"Bis zu fünf Produktlinien, über 180 Festpreis-Sprints seit 2023", industry:"Industrials & Manufacturing", filter:"industrial", outcome:"scale", discipline:"software-cloud", image:"software", metric:"180+", label:"Festpreis-Sprints seit 2023",
    facts:[
      "B2B-Plattformen für Rückführung und Wiederaufbereitung von Altteilen, Tochter eines Industriekonzerns",
      "Bis zu fünf Produktlinien parallel, je Linie ein festes Team aus Deutschland und Rumänien",
      "Rahmenvertrag für agile Entwicklung, eine Bestellung je Sprint von zwei bis drei Wochen",
      "Seit 03/2023 laufend, über 40 Monate",
      "rund 4,3 Mio. € beauftragt",
      "Festpreis je Sprint mit Abnahme",
    ],
    challenge:[
      "Mehrere Produktlinien mit eigenen Roadmaps gleichzeitig weiterentwickeln",
      "Agile Geschwindigkeit mit Ergebnissicherheit: bestellen und abnehmen je Sprint",
      "Neue Themen im selben Modell starten, ohne neue Vertragsverhandlung",
    ],
    solution:[
      "Festes Team je Linie, Festpreis je Sprint aus Kapazität und Sprintlänge",
      "Eine Bestellnummer je Sprint, Abnahme nach dem agilen Ansatz des Rahmenvertrags",
      "DevOps-Rollen in den Kernlinien",
      "Einstieg 2022 über Ticket-Kontingent, seit 2023 vollständig im Sprint-Modell",
    ],
    results:[
      "Über 180 Sprints bestellt und abgenommen, 55 Sprint-Bestellungen allein 2025",
      "Drei neue Produktlinien seit 2024 im gleichen Modell gestartet",
      "Rahmenvertrag 2023 verlängert, Zusammenarbeit im vierten Jahr",
    ]},
  {slug:"funktionsbetreuung-infotainment", name:"Funktionsbetreuung Infotainment", headline:"Rund 20 Park- und Online-Funktionen, Rahmenkontrakt 2020 bis 2024", industry:"Automotive", filter:"industrial automotive", outcome:"optimize scale", discipline:"system-engineering", image:"automotive", metric:"20", label:"Park- und Online-Funktionen",
    facts:[
      "Globaler Automobilhersteller, Elektronik-Entwicklung Infotainment",
      "Rund 20 vernetzte Funktionen: 13 Parkfunktionen, 8 Online-Services, zwei Infotainment-Generationen",
      "Anforderungsanalyse, Testkonzept und Volltest, Lieferantenbetreuung mit Ticketbearbeitung",
      "Rahmenkontrakt 2020 bis 2024, 10,7 Mio. €, 24 Abrufe",
      "Werkvertrag, Katalogpreis je Funktion, Abnahme je Paket",
    ],
    challenge:[
      "Funktionsumfang und Änderungsrate übersteigen die interne Betreuungskapazität",
      "Jede Funktion braucht Anforderungen, Testkonzept und Volltest je Software-Stand",
      "Fehler aus Absicherung und Feld mit Zulieferern bis zur Lösung verfolgen",
    ],
    solution:[
      "Funktionsverantwortung je Funktion als Werk, Preis nach Katalog und Komplexität",
      "Anforderungsanalyse und Spezifikation, Testkonzept und Volltest im Fahrzeug",
      "Lieferantenbetreuung mit Ticketbearbeitung bis zur gelösten Fehlermeldung",
      "Abnahme je Arbeitspaket, Meilenstein-Reviews je Quartal",
    ],
    results:[
      "Kontrakt zweimal erweitert, Zielwert von 8,6 auf 10,7 Mio. €",
      "24 Abrufe abgenommen",
      "Folgeaufträge 2025/26, dazu 5,9 Mio. € für die nächste Plattformgeneration",
    ]},
  {slug:"penetrationstests", name:"Penetrationstests für Mittelstand und KRITIS", headline:"30 Tests bei 19 Kunden seit 2023, von Steuergeräten bis Web-Anwendungen", industry:"Mittelstand & KRITIS", filter:"energy aerospace industrial technology health", outcome:"optimize", discipline:"cyber-compliance", image:"penetrationstests", metric:"30", label:"Tests bei 19 Kunden seit 2023",
    facts:[
      "19 Unternehmen aus Energie, Luftfahrt, Maschinenbau, Software, Gesundheitsabrechnung, Telekommunikation",
      "Recon, Blackbox, Greybox, Whitebox; Web, Infrastruktur, Active Directory, Steuergeräte und Hardware",
      "Eigene Pentester und Partner unter Emposo-Leitung, Permission to Attack als Vertragsanlage",
      "23 Aufträge seit 09/2023, 4.000 bis 26.000 € je Test",
      "seit 2024 Festpreis",
      "Bericht und Retest",
    ],
    challenge:[
      "Regelmäßige Prüfungen mit belastbarem Bericht, aber kein eigenes Offensive-Security-Team",
      "Steuergeräte und Hardware brauchen andere Methoden als Web-Anwendungen",
      "Ergebnisse müssen priorisiert und im Retest nachprüfbar sein",
    ],
    solution:[
      "Scoping je Umgebung, Testart nach Fragestellung",
      "Eigene Pentester, für Steuergeräte und Hardware spezialisierte Partner unter Emposo-Leitung",
      "Bericht mit priorisierten Maßnahmen und Erläuterung, Nachweise nach 90 Tagen gelöscht",
      "Retest nach Behebung, bei Wiederholkunden jährlich",
    ],
    results:[
      "30 Aufträge bei 19 Kunden in drei Jahren, drei Wiederholkunden",
      "Steuergeräte-Pentest für einen Maschinenbaukonzern, KRITIS-Prüfungen in Energie und Luftfahrt",
      "Werkvertragskunden beauftragen die Pentests zusätzlich",
    ]},
  {slug:"cybersecurity-post-market", name:"Cybersecurity im Post-Market für Medizinprodukte", headline:"Schwachstellenscans für 20 Produktstände in sechs Monaten", industry:"Health & Pharma", filter:"health", outcome:"optimize", discipline:"cyber-compliance", image:"cybersecurity-medizin", metric:"20", label:"Produktstände in sechs Monaten",
    facts:[
      "Medizintechnik-Hersteller für Augenheilkunde, Software-Qualitätsmanagement",
      "Cybersecurity-Monitoring für rund 20 Produktstände in vier Gerätefamilien",
      "Post-Market-Surveillance nach MDR und FDA, Arbeit nach der Software-SOP des Kunden",
      "Projekt: 6 Monate",
      "ca. 250.000 €",
      "Werkvertrag, Festpreis in drei Paketen, monatliche Abnahme",
    ],
    challenge:[
      "MDR und FDA verlangen Cybersecurity-Überwachung über den gesamten Produktlebenszyklus",
      "Scans und Monitoring-Dokumente für viele Bestandsprodukte binden das interne SW-QM",
      "Jeder Nachweis muss je Produkt und Version dokumentiert und prüfbar sein",
    ],
    solution:[
      "Schwachstellenscans der Software-Komponenten (Black Duck) und Netzwerkschnittstellen (Nessus)",
      "Auswertung vorhandener Assessments, Informationsbasen und Änderungsprotokolle",
      "Entwurf der Monitoring-Dokumente nach Kunden-SOP, Abnahme im monatlichen Statusreview",
    ],
    results:[
      "20 Produktstände in drei Arbeitspaketen abgenommen",
      "Nachweisbasis für das Post-Market-Review nach MDR und FDA",
      "Laufzeit auf Kundenwunsch verkürzt, Festpreis und Bestellrahmen eingehalten",
    ]},
  {slug:"informationssicherheits-risikomanagement", name:"Informationssicherheits-Risikomanagement in der Medizintechnik", headline:"Risikobewertung und Trainings in zehn Gesellschaften auf drei Kontinenten", industry:"Health & Pharma", filter:"health", outcome:"transform optimize", discipline:"cyber-compliance", image:"risikomanagement", metric:"10", label:"Gesellschaften auf drei Kontinenten",
    facts:[
      "Globaler Medizintechnik-Hersteller in Familienbesitz, Neukunde 2024",
      "Risikomanagement in der Zentrale und zehn Tochtergesellschaften in Nordamerika und Asien",
      "Folgepaket: Begleitung eines SAP-Sicherheitsaudits über acht Systeme",
      "Februar bis Dezember 2024",
      "ca. 250.000 €",
      "Rahmenvertrag Werkleistung, sieben Pakete mit Teilabnahme",
    ],
    challenge:[
      "Methodik und Vorlagen vorhanden, Bewertung und Rollout in die Organisation fehlten",
      "Vorbereitung auf das ISO/IEC-27001-Audit mit Gap-Analyse und Maßnahmen bis Jahresende",
      "Drittparteien- und Projektrisiken weltweit nach einem Verfahren bewerten",
    ],
    solution:[
      "50 Risikobewertungen nach Kundenmethodik: 25 Drittparteien, 25 Projekte",
      "Vier Risikokataloge und fünf Prozesstrainings",
      "Third-Party-Risikomanagement in zehn Tochtergesellschaften ausgerollt, mit Key-User-Support",
      "Strategie-Workshop vor Ort, Security-Expertise und Nachweise für das SAP-Audit",
    ],
    results:[
      "Sieben Arbeitspakete mit Lieferterminen je Quartal abgenommen",
      "Auditvorbereitung ISO/IEC 27001 abgeschlossen, Maßnahmen je Quartal berichtet",
      "Risiken aus Projekten, Produkten und Lieferanten nach einem konzernweiten Verfahren bewertet",
    ]},
  {slug:"fuzzing-firmware", name:"Fuzzing für sicherheitsrelevante Firmware", headline:"Drei Kampagnen in drei Jahren: Trusted Firmware-M, TPM-Firmware, Bluetooth-Stack", industry:"Halbleiter", filter:"technology", outcome:"optimize", discipline:"cyber-compliance", image:"fuzzing", metric:"3", label:"Fuzzing-Kampagnen in drei Jahren",
    facts:[
      "Globaler Halbleiterhersteller, Security-Software für Mikrocontroller in IoT- und Sicherheitsprodukten",
      "Fuzzing gegen Trusted Firmware-M (2024), TPM-Firmware (2025), Bluetooth-Stack (2026)",
      "Firmware-Rehosting, Schwachstellenberichte mit CVSS 3.1 und Proof of Concept",
      "Drei Aufträge 2024 bis 2026",
      "ca. 235.000 €",
      "Festpreis mit messbaren Abnahmekriterien",
    ],
    challenge:[
      "Schwachstellen in der Firmware wirken direkt in die Produkte der Kunden",
      "Unerwartete Eingaben an der Grenze zwischen sicherer und unsicherer Welt systematisch prüfen",
      "Der Kunde will nach der Kampagne selbst weiterfuzzen",
    ],
    solution:[
      "Testfirmware und Fuzzer-Konfiguration je Ziel, Abdeckungsziel 80 % Funktionen, 70 % Code",
      "Setup-Gültigkeit über künstlich eingebaute Schwachstellen nachgewiesen",
      "Jede Schwachstelle mit Bericht, CVSS 3.1 und reproduzierbarem Proof of Concept",
      "Reproduzierbares Docker-Setup an den Kunden übergeben",
    ],
    results:[
      "Schwachstellen vor Auslieferung gefunden, bewertet und nachgewiesen",
      "Kampagnen 2024 und 2025 gegen Abdeckungsziele abgenommen, dritte läuft",
      "Derselbe Anforderer beauftragt drei Kampagnen in drei Jahren",
    ]},
];

// Stellenausschreibungen (owner delivery 24.09.2026, 2026-09-24_Stellen.pptx,
// verbatim; the per-posting "Über Emposo" boilerplate is omitted — the site is
// that context). Rendered by jobs() in render.mjs on /karriere/.
export const jobs = [
  {
    slug: 'fullstack-solution-architect',
    title: 'Fullstack Solution Architect (m/w/d)',
    meta: ['Deutschlandweit', 'Remote / Hybrid', 'Unbefristete Festanstellung', 'Start: Nach Vereinbarung'],
    tagline: 'Gestalte mit uns die Zukunft moderner Softwarelösungen',
    intro: [
      'Du brennst für moderne Softwarearchitekturen und möchtest innovative Anwendungen von der ersten Idee bis zum produktiven Betrieb mitgestalten? Du begeisterst Dich für Fullstack-Entwicklung, Cloud-Technologien und moderne DevOps-Ansätze?',
      'Dann werde Teil von Emposo und unterstütze unsere Kunden bei der Entwicklung zukunftssicherer Softwarelösungen. Als Fullstack Solution Architect (m/w/d) übernimmst Du eine zentrale Rolle bei der technischen Beratung, Architektur und Umsetzung anspruchsvoller Softwareprojekte. Du entwickelst innovative Lösungen, berätst Kunden bei strategischen Technologieentscheidungen und begleitest Projekte von der Anforderungsaufnahme bis zum erfolgreichen Go-Live.',
    ],
    sections: [
      {title: 'Deine Aufgaben', items: [
        'Technische Beratung und Lösungsentwicklung in der Projektanbahnung mit Kunden',
        'Konzeption und Umsetzung moderner Software- und Weblösungen im Frontend-, Backend- und DevOps-Umfeld',
        'Erstellung technischer Angebote, Konzepte und Aufwandsschätzungen',
        'Verantwortung für Architektur, Qualität, Wartbarkeit und Skalierbarkeit der entwickelten Lösungen',
        'Analyse fachlicher Anforderungen und Übersetzung in nachhaltige technische Architekturen',
        'Auswahl und Bewertung geeigneter Technologien, Frameworks und Plattformen',
        'Enge Zusammenarbeit mit internen Stakeholdern, Kunden und externen Partnern',
        'Technische Führung und Unterstützung interdisziplinärer Projektteams',
        'Durchführung von Architektur-Reviews, Workshops und technischen Präsentationen',
        'Begleitung von Projekten von der Konzeptionsphase bis zur produktiven Einführung',
      ]},
      {title: 'Dein Profil', items: [
        'Mehrjährige Berufserfahrung als Fullstack Solution Architect, Software Architect, Solution Architect, Lead Developer oder in einer vergleichbaren Rolle',
        'Langjährige Erfahrung in der Entwicklung moderner Softwarelösungen mit Technologien wie Java, Node.js, JavaScript/TypeScript, .NET, Python oder PHP',
        'Sehr gute Kenntnisse moderner Frontend-Technologien wie React, Angular oder vergleichbare Frameworks',
        'Erfahrung mit Cloud-Plattformen wie Microsoft Azure, AWS oder Google Cloud',
        'Fundierte Kenntnisse in DevOps, CI/CD sowie Container-Technologien wie Docker und Kubernetes',
        'Tiefes Verständnis für Softwarearchitekturen, Design Patterns und Best Practices der modernen Softwareentwicklung',
        'Erfahrung in Kundenkommunikation, technischer Projektleitung sowie in der Projekt- und Vertragsanbahnung',
        'Ausgeprägte Kommunikationsfähigkeit, Eigeninitiative und Lösungsorientierung',
        'Verhandlungssichere Deutschkenntnisse sowie gute Englischkenntnisse',
      ]},
      {title: 'Nice to have', items: [
        'Erfahrung mit Microservices-Architekturen und Event-Driven Architectures',
        'Kenntnisse in WPF, WCF oder anderen Enterprise-Technologien',
        'Erfahrung mit Infrastructure as Code (Terraform, Bicep oder vergleichbar)',
        'Zertifizierungen im Bereich Cloud, Software Architecture oder DevOps (z. B. Azure, AWS, Kubernetes, iSAQB oder TOGAF)',
        'Erfahrung in der fachlichen Führung technischer Teams und großer Softwareprojekte',
      ]},
      {title: 'Das erwartet Dich bei Emposo', items: [
        'Spannende Projekte bei namhaften Großkunden und führenden Unternehmen unterschiedlichster Branchen',
        'Hoher Gestaltungsspielraum und viel Eigenverantwortung',
        'Moderne Technologien und innovative Softwareprojekte',
        'Kontinuierliche Weiterbildung und Zertifizierungsmöglichkeiten',
        'Flexible Arbeitszeiten und überwiegend mobiles Arbeiten',
        'Flache Hierarchien und schnelle Entscheidungswege',
        'Persönliche Entwicklungsmöglichkeiten in einem wachsenden Unternehmen',
        'Kollegiales Umfeld mit offener Unternehmenskultur',
      ]},
      {title: 'Rahmenbedingungen', items: [
        'Unbefristete Festanstellung',
        'Vollzeit (40 Stunden/Woche)',
        'Deutschlandweit, überwiegend Remote',
        'Attraktives Vergütungsmodell',
        'Start nach Vereinbarung',
      ]},
    ],
    apply: 'Dann freuen wir uns auf Deine Bewerbung inklusive Angabe Deines frühestmöglichen Eintrittstermins und Deiner Gehaltsvorstellung.',
  },
  {
    slug: 'data-ai-solution-architect',
    title: 'Data & AI Solution Architect (m/w/d)',
    meta: ['Deutschlandweit', 'Remote / Hybrid', 'Unbefristete Festanstellung', 'Start: Nach Vereinbarung'],
    tagline: 'Gestalte mit uns die Zukunft von Data & AI',
    intro: [
      'Du möchtest Unternehmen dabei unterstützen, aus Daten echten Mehrwert zu schaffen und innovative KI-Lösungen zu entwickeln? Du begeisterst dich für moderne Datenplattformen, Cloud-Technologien und Generative AI?',
      'Dann werde Teil von Emposo und gestalte gemeinsam mit unseren Kunden die nächste Generation datengetriebener Lösungen. Als Data & AI Solution Architect (m/w/d) übernimmst Du eine zentrale Rolle bei der Entwicklung moderner Daten- und KI-Architekturen. Du berätst Kunden bei strategischen Technologieentscheidungen und entwickelst innovative Lösungen rund um Data Analytics, Cloud und Artificial Intelligence.',
    ],
    sections: [
      {title: 'Deine Aufgaben', items: [
        'Konzeption und Architektur moderner Data-, Analytics- und AI-Lösungen',
        'Entwicklung skalierbarer Datenplattformen auf Basis von Data Lakes und Data Warehouses',
        'Design und Einführung von Generative-AI-Lösungen wie Large Language Models (LLMs), Retrieval Augmented Generation (RAG) und AI Agents',
        'Analyse fachlicher Anforderungen und Übersetzung in nachhaltige technische Lösungsarchitekturen',
        'Beratung unserer Kunden zu Datenstrategien, Cloud-Architekturen und AI-Use-Cases',
        'Auswahl und Bewertung geeigneter Technologien und Plattformen',
        'Definition von Architektur-, Security- und Governance-Standards',
        'Begleitung von Projekten von der Ideenphase über Proof of Concepts bis zur produktiven Einführung',
        'Technische Steuerung und Unterstützung interdisziplinärer Projektteams',
        'Durchführung von Workshops und Architektur-Reviews bei Kunden',
      ]},
      {title: 'Dein Profil', items: [
        'Mehrjährige Berufserfahrung als Solution Architect, Data Architect, AI Architect oder vergleichbar',
        'Fundierte Kenntnisse in Data Engineering, Analytics und Cloud-Technologien',
        'Erfahrung mit modernen Datenplattformen wie Databricks, Snowflake oder vergleichbaren Lösungen',
        'Praxiserfahrung im Bereich Machine Learning und Generative AI',
        'Kenntnisse in Microsoft Azure, AWS oder Google Cloud',
        'Erfahrung mit Datenarchitekturen, Data Governance und Security-Konzepten',
        'Ausgeprägte Kommunikations- und Beratungskompetenz',
        'Verhandlungssichere Deutschkenntnisse sowie gute Englischkenntnisse',
      ]},
      {title: 'Nice to have', items: [
        'Erfahrung mit MLOps- und AI-Plattformen',
        'Kenntnisse in RAG-Architekturen, Vector Databases und AI Agents',
        'Zertifizierungen im Bereich Cloud, Data oder Enterprise Architecture (z. B. Azure, AWS, Databricks, TOGAF)',
        'Erfahrung in der Leitung technischer Teams oder großer Transformationsprojekte',
      ]},
      {title: 'Das erwartet Dich bei Emposo', items: [
        'Spannende Projekte bei namhaften Kunden unterschiedlicher Branchen',
        'Hoher Gestaltungsspielraum und viel Eigenverantwortung',
        'Moderne Technologien rund um Data, Cloud und Artificial Intelligence',
        'Kontinuierliche Weiterbildung und Zertifizierungsmöglichkeiten',
        'Flexible Arbeitszeiten und überwiegend mobiles Arbeiten',
        'Flache Hierarchien und schnelle Entscheidungswege',
        'Persönliche Entwicklungsmöglichkeiten in einem wachsenden Unternehmen',
        'Kollegiales Umfeld mit offener Unternehmenskultur',
      ]},
      {title: 'Rahmenbedingungen', items: [
        'Unbefristete Festanstellung',
        'Vollzeit (40 Stunden/Woche)',
        'Deutschlandweit, überwiegend Remote',
        'Attraktives Vergütungsmodell',
        'Start zum nächstmöglichen Zeitpunkt',
      ]},
    ],
    apply: 'Dann freuen wir uns auf Deine Bewerbung inklusive Angabe Deines frühestmöglichen Eintrittstermins und Deiner Gehaltsvorstellung.',
  },
];
