// Editorial source: Emposo_Website Struktur (2).xlsx, visible sheets and final
// proposal columns. Keep project claims in this one place.
// Disciplines have no detail pages (workbook v2: "Im Bereich Leistungen gibt es
// keine Unterseiten"); `overview` names the grouped Engineering/Technology page.
// `focus` and `detail` come from the workbook's Unterpunkte/statement columns.
export const disciplines = [
  {slug:'system-engineering', name:'System Engineering & Entwicklung', group:'Engineering', overview:'/expertise/engineering/', image:'automotive', topics:'Anforderungen, Modellierung, Entwicklung und Embedded Systems.', focus:['Anforderungen','Modellierung','Entwicklung','Embedded Systems'], detail:'Anforderungen, Modellierung, Entwicklung und Embedded Systems werden zu einer abgesicherten Funktion verbunden — als definierter Umfang mit Abnahme.', promise:'Wir übernehmen definierte Entwicklungsumfänge von der Anforderung bis zur abgesicherten Funktion.'},
  {slug:'produktion-industrialisierung', name:'Produktion & Industrialisierung', group:'Engineering', overview:'/expertise/engineering/', image:'logistics', topics:'Qualität, Logistik, Automatisierung, Anlagenintegration und Prozessoptimierung.', focus:['Qualität','Logistik','Automatisierung','Anlagenintegration','Prozessoptimierung'], detail:'Qualität, Logistik, Automatisierung, Anlagenintegration und Prozessoptimierung greifen ineinander, damit technische Abläufe stabil laufen.', promise:'Wir industrialisieren Prozesse, Datenflüsse und technische Abläufe für einen stabilen Betrieb.'},
  {slug:'test-validierung', name:'Test, Validierung & Integration', group:'Engineering', overview:'/expertise/engineering/', image:'vehicle-testing', topics:'Integration und Test, Safety, Quality Gates und revisionssichere Nachweise.', focus:['Teststrategie','Testautomatisierung','Integration','Safety','Quality Gates','Revisionssichere Nachweise'], detail:'Teststrategie, Automatisierung, Integration und Safety führen zu Quality Gates und revisionssicheren Nachweisen für belastbare Freigaben.', promise:'Wir machen Qualität, Sicherheit und Freigabeentscheidungen belastbar.'},
  {slug:'engineering-services', name:'Engineering Services', group:'Engineering', overview:'/expertise/engineering/', image:'collaboration', topics:'PMO, Change, Audit und technische Dokumentation.', focus:['PMO','Change','Audit','Technische Dokumentation','Reporting','Konfigurationsmanagement'], detail:'PMO, Change, Audit, technische Dokumentation, Reporting und Konfigurationsmanagement — als Dauerleistung mit klar abgegrenztem Ergebnis.', promise:'Wir liefern technische Steuerung und Dokumentation als messbare, abgegrenzte Werkleistung.'},
  {slug:'ai-daten', name:'AI-Transformation & Daten', group:'Technology', overview:'/expertise/technology/', image:'data2ai', topics:'AI-Strategie, Agentic AI, Datenplattformen, MLOps und Training.', focus:['AI-Strategie','Agentic AI','Knowledge Graphs','RAG','Datenplattformen','MLOps','Training'], detail:'AI-Strategie, Agentic AI, Knowledge Graphs, Datenplattformen und MLOps führen Daten und Wissen in produktive Anwendungen.', promise:'Wir überführen Daten und Wissen in produktive, nachvollziehbare AI-Anwendungen.'},
  {slug:'software-cloud', name:'Software, Cloud & Architecture', group:'Technology', overview:'/expertise/technology/', image:'software', topics:'Solution Architecture, Multi-Cloud, Fullstack und DevSecOps.', focus:['Solution Architecture','Multi-Cloud','Fullstack','APIs','CI/CD','DevSecOps','Plattformintegration'], detail:'Solution Architecture, Multi-Cloud, Fullstack-Entwicklung, APIs, CI/CD und DevSecOps tragen Plattformen und Anwendungen bis in den produktiven Betrieb.', promise:'Wir bauen und transformieren Plattformen, Anwendungen und Architekturen bis zum produktiven Betrieb.'},
  {slug:'cyber-compliance', name:'Cyber & Compliance', group:'Technology', overview:'/expertise/technology/', image:'technology', topics:'Cyber Security, Penetration Testing, GxP und EU AI Act.', focus:['Cyber Security','Security Architecture','Penetration Testing','GxP','EU AI Act','Auditfähige Nachweise'], detail:'Cyber Security, Security Architecture, Penetration Testing sowie GxP- und EU-AI-Act-Anforderungen werden Teil von Architektur, Prozessen und Lieferung.', promise:'Wir integrieren Sicherheit und Compliance in Architektur, Prozesse und Lieferung.'},
  {slug:'enterprise-services', name:'Enterprise Services', group:'Technology', overview:'/expertise/technology/', image:'datacenter', topics:'Managed Services, Migration, Integration und S/4HANA.', focus:['Managed Services','Migration','Integration','S/4HANA','SLA-gesteuerter Betrieb'], detail:'Managed Services, Migration, Integration und S/4HANA — betrieben mit vereinbarten Service-Leveln, Reaktionszeiten und Eskalationswegen.', promise:'Wir übernehmen Migration, Integration und Betrieb mit klarer Service- und Ergebnisverantwortung.'},
];

export const industries = [
  {slug:'aerospace-defense', name:'Aerospace & Defense', image:'industry-aerospace', filter:'aerospace', intro:'Engineering, Integration und belastbare Nachweise für komplexe technische Systeme.', challenge:'Komplexe Systeme brauchen durchgängige Anforderungen, abgestimmte Entwicklungsprozesse und nachvollziehbare Freigaben.', delivery:'Wir verbinden Systementwicklung, Test und technische Dokumentation zu klar definierten Leistungen.', disciplines:['system-engineering','test-validierung','engineering-services'], cases:[]},
  {slug:'energy-resources', name:'Energy & Resources', image:'industry-energy', filter:'energy', intro:'Stabile Systeme und verlässliche Services für eine Branche im Wandel.', challenge:'Kritische Prozesse müssen zuverlässig laufen, während sich Technologien und Anforderungen weiterentwickeln.', delivery:'Wir übernehmen Integration und laufende Services mit vereinbarten Service-Leveln, Reaktionszeiten und Eskalationswegen.', disciplines:['software-cloud','enterprise-services'], cases:['managed-service']},
  {slug:'health-pharma', name:'Health & Pharma', image:'industry-health', filter:'health', intro:'Technologie, Validierung und Qualität im regulierten Umfeld.', challenge:'Neue Technologien und aktualisierte KI-Modelle müssen sich in geregelte Prüf- und Freigabeprozesse einfügen.', delivery:'Wir verzahnen AI, Test und Compliance mit den Anforderungen Ihrer produktiven Umgebung.', disciplines:['test-validierung','ai-daten','cyber-compliance'], cases:['mlops-medizinprodukte','multi-site-transition']},
  {slug:'industrials-manufacturing', name:'Industrials & Manufacturing', subtitle:'Inklusive Automotive', image:'industry-industrials', filter:'industrial', intro:'Von der Fahrzeugentwicklung bis zum Werk: Engineering und Technology greifen ineinander.', challenge:'Verteiltes Engineering-Wissen, komplexe Fahrzeugfunktionen und industrielle Abläufe brauchen eine gemeinsame technische Grundlage.', delivery:'Wir verbinden Entwicklung, Produktion, Tests und Daten, damit Wissen nutzbar wird und Prozesse stabil laufen.', disciplines:['system-engineering','produktion-industrialisierung','test-validierung','engineering-services','ai-daten'], cases:['data2ai-platform','engineering-wissensbasis','wissens-assistent','homologationstests','fahrzeugfunktionen','technische-dokumentation','rechenzentrums-umzug']},
  {slug:'technology-telecoms-media', name:'Technology, Telecoms & Media', image:'industry-technology', filter:'technology', intro:'Digitale Produkte, sichere Plattformen und skalierbare Architekturen.', challenge:'Anwendungen, Daten und bestehende Systeme müssen sich auch bei wachsenden Anforderungen zuverlässig verbinden lassen.', delivery:'Wir führen Software, Cloud, Security und Datenkompetenz bis zum produktiven Betrieb zusammen.', disciplines:['ai-daten','software-cloud','cyber-compliance','enterprise-services'], cases:[]},
];

export const projects = [
  {slug:'data2ai-platform', name:'Data2AI Plattform', headline:'Aus verteilten Engineering-Daten wird produktive KI.', industry:'Automotive', filter:'industrial automotive', outcome:'transform', discipline:'ai-daten', image:'data2ai', metric:'7×', label:'Produktivitätssteigerung', challenge:'Verteilte Engineering-Daten sollen als gemeinsame Grundlage für produktive KI nutzbar werden.', solution:'Eine Data2AI Plattform verbindet Engineering-Daten und Wissen für die Anwendung im Betrieb.', results:['7-fache Produktivitätssteigerung','ROI innerhalb von 9 Monaten','PoC in weniger als 4 Wochen']},
  {slug:'engineering-wissensbasis', name:'Vernetzte Engineering-Wissensbasis', headline:'Von Wochen auf Stunden: Engineering-Wissen wird ausführbar.', industry:'Automotive', filter:'industrial automotive', outcome:'transform', discipline:'ai-daten', image:'engineering-knowledge', metric:'83 %', label:'weniger Aufwand bei Testspezifikationen', challenge:'Engineering-Wissen muss für Testspezifikationen verfügbar und über die Entwicklung hinweg nachvollziehbar sein.', solution:'Eine vernetzte Wissensbasis macht Engineering-Wissen ausführbar und unterstützt die Erstellung von Testspezifikationen.', results:['83 % weniger Aufwand bei Testspezifikationen','Vollständige Traceability']},
  {slug:'rechenzentrums-umzug', name:'Rechenzentrums-Umzug ohne Stillstand', headline:'Transformation ohne eine Minute migrationsbedingten Stillstand.', industry:'Automotive', filter:'industrial automotive', outcome:'transform', discipline:'enterprise-services', image:'datacenter', metric:'0', label:'Minuten migrationsbedingter Stillstand', challenge:'Ein Rechenzentrum muss umziehen, während Produktion und Logistik durchgängig verfügbar bleiben.', solution:'Migration und Integration werden auf den fortlaufenden Betrieb von Produktion und Logistik ausgerichtet.', results:['Keine migrationsbedingte Betriebsunterbrechung','Produktion und Logistik durchgängig verfügbar']},
  {slug:'mlops-medizinprodukte', name:'MLOps für Medizinprodukte', headline:'KI-Modelle regulatorisch sicher und schneller aktualisieren.', industry:'Health & Pharma', filter:'health', outcome:'transform', discipline:'ai-daten', image:'pharma', metric:'>70 %', label:'weniger Prüfaufwand', challenge:'KI-Modelle für Medizinprodukte müssen aktualisiert und ihre Änderungen regulatorisch sicher geprüft werden.', solution:'MLOps verbindet die Aktualisierung der KI-Modelle mit den notwendigen Prüf- und Freigabeabläufen.', results:['Über 70 % weniger Prüfaufwand','Updates in Tagen statt Wochen']},
  {slug:'wissens-assistent', name:'Wissens-Assistent Engineering', headline:'Technisches Wissen in Sekunden statt Tagen verfügbar.', industry:'Industrials & Manufacturing', filter:'industrial', outcome:'transform', discipline:'ai-daten', image:'software', metric:'80.000 €', label:'bis zu dieser Summe monatlich an Rechercheaufwand eingespart', challenge:'Die Recherche nach technischem Wissen bindet Zeit in der täglichen Engineering-Arbeit.', solution:'Ein Wissens-Assistent macht technisches Wissen für die tägliche Anwendung verfügbar.', results:['Technisches Wissen in Sekunden statt Tagen verfügbar','Bis zu 80.000 EUR Rechercheaufwand pro Monat eingespart']},
  {slug:'multi-site-transition', name:'Multi-Site Transition Program', headline:'27+ Beauftragungen termingerecht und auditfest abgenommen.', industry:'Health & Pharma', filter:'health', outcome:'scale', discipline:'cyber-compliance', image:'pharma-transition', metric:'27+', label:'Beauftragungen termingerecht und auditfest abgenommen', challenge:'Ein Transition-Programm muss über mehrere Standorte hinweg termingerecht und auditfest umgesetzt werden.', solution:'Ein standortübergreifendes Programm führt die Beauftragungen zur Abnahme und schafft einen wiederverwendbaren Rollout-Blueprint.', results:['27+ Beauftragungen termingerecht und auditfest abgenommen','Quality-Team entlastet','Rollout-Blueprint für weitere Standorte etabliert']},
  {slug:'homologationstests', name:'Zulassungs- und Homologationstests', headline:'Markteinführung über mehrere Fahrzeugwellen abgesichert.', industry:'Automotive', filter:'industrial automotive', outcome:'optimize', discipline:'test-validierung', image:'vehicle-testing', metric:'Zulassung', label:'termingerecht abgesichert', challenge:'Mehrere Fahrzeugwellen benötigen belastbare Tests und Nachweise für ihre Markteinführung.', solution:'Zulassungs- und Homologationstests sichern die Freigaben mit vollständigen revisionssicheren Nachweisen ab.', results:['Zulassungstermine eingehalten','Vollständige revisionssichere Nachweise']},
  {slug:'managed-service', name:'Managed Service seit 2018', headline:'Langfristige Betriebssicherheit mit klaren SLAs.', industry:'Energy & Resources', filter:'energy', outcome:'optimize', discipline:'enterprise-services', image:'wind-energy', metric:'8+', label:'Jahre stabiler Betrieb', challenge:'Ein laufender Service braucht dauerhaft verlässliche Leistung und klar definierte Service-Level.', solution:'Ein langfristiger Managed Service übernimmt den Betrieb mit klar vereinbarten SLAs.', results:['Über 8 Jahre stabiler Betrieb','Keine SLA-Verletzungen']},
  {slug:'fahrzeugfunktionen', name:'Fahrzeugfunktionen als Langzeit-Werkprogramm', headline:'Fünf Jahre planbare Lieferung kompletter Funktionsumfänge.', industry:'Automotive', filter:'industrial automotive', outcome:'scale', discipline:'system-engineering', image:'automotive', metric:'5', label:'Jahre planbare Lieferung', challenge:'Komplette Fahrzeugfunktionen müssen über ein mehrjähriges Programm hinweg planbar geliefert werden.', solution:'Ein Langzeit-Werkprogramm bündelt die Lieferung kompletter Funktionsumfänge.', results:['Termingerechte Lieferung','Planungs- und Budgetsicherheit','Fünf Jahre planbare Lieferung']},
  {slug:'technische-dokumentation', name:'Technische Dokumentation als Dauerleistung', headline:'800 technische Dokumente pro Jahr, skalierbar geliefert.', industry:'Industrials & Manufacturing', filter:'industrial', outcome:'optimize', discipline:'engineering-services', image:'collaboration', metric:'800', label:'technische Dokumente pro Jahr', challenge:'Produktfreigaben benötigen dauerhaft konsistente technische Dokumentation.', solution:'Technische Dokumentation wird als skalierbare Dauerleistung bereitgestellt.', results:['800 technische Dokumente pro Jahr','Produktfreigaben abgesichert','Konsistente Qualität über mehr als 6 Jahre']},
];
